version: 2
updates:
- package-ecosystem: nuget
  directories:
    - "/DevProxy.Hosting"
  schedule:
    interval: daily

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily